export const COUNTRY_CODES: Record<string, string> = {
  "Argentina": "ARG",
  "Algeria": "ALG",
  "Australia": "AUS",
  "Austria": "AUT",
  "Belgium": "BEL",
  "Bosnia and Herzegovina": "BIH",
  "Brazil": "BRA",
  "Canada": "CAN",
  "Cape Verde": "CPV",
  "Colombia": "COL",
  "Costa Rica": "CRC",
  "Croatia": "CRO",
  "Curacao": "CUW",
  "Czechia": "CZE",
  "DR Congo": "COD",
  "Ecuador": "ECU",
  "Egypt": "EGY",
  "England": "ENG",
  "France": "FRA",
  "Germany": "GER",
  "Ghana": "GHA",
  "Haiti": "HAI",
  "Iran": "IRN",
  "Iraq": "IRQ",
  "Japan": "JPN",
  "Jordan": "JOR",
  "Korea Republic": "KOR",
  "Mexico": "MEX",
  "Morocco": "MAR",
  "Netherlands": "NED",
  "New Zealand": "NZL",
  "Norway": "NOR",
  "Panama": "PAN",
  "Paraguay": "PAR",
  "Portugal": "POR",
  "Qatar": "QAT",
  "Saudi Arabia": "KSA",
  "Scotland": "SCO",
  "Senegal": "SEN",
  "South Africa": "RSA",
  "Spain": "ESP",
  "Sweden": "SWE",
  "Switzerland": "SUI",
  "Tunisia": "TUN",
  "Turkiye": "TUR",
  "United States": "USA",
  "Uruguay": "URU",
  "Uzbekistan": "UZB"
};

export const CONFEDERATIONS: Record<string, "AFC" | "CAF" | "CONCACAF" | "CONMEBOL" | "OFC" | "UEFA"> = {
  "Argentina": "CONMEBOL",
  "Algeria": "CAF",
  "Australia": "AFC",
  "Austria": "UEFA",
  "Belgium": "UEFA",
  "Bosnia and Herzegovina": "UEFA",
  "Brazil": "CONMEBOL",
  "Canada": "CONCACAF",
  "Cape Verde": "CAF",
  "Colombia": "CONMEBOL",
  "Costa Rica": "CONCACAF",
  "Croatia": "UEFA",
  "Curacao": "CONCACAF",
  "Czechia": "UEFA",
  "DR Congo": "CAF",
  "Ecuador": "CONMEBOL",
  "Egypt": "CAF",
  "England": "UEFA",
  "France": "UEFA",
  "Germany": "UEFA",
  "Ghana": "CAF",
  "Haiti": "CONCACAF",
  "Iran": "AFC",
  "Iraq": "AFC",
  "Japan": "AFC",
  "Jordan": "AFC",
  "Korea Republic": "AFC",
  "Mexico": "CONCACAF",
  "Morocco": "CAF",
  "Netherlands": "UEFA",
  "New Zealand": "OFC",
  "Norway": "UEFA",
  "Panama": "CONCACAF",
  "Paraguay": "CONMEBOL",
  "Portugal": "UEFA",
  "Qatar": "AFC",
  "Saudi Arabia": "AFC",
  "Scotland": "UEFA",
  "Senegal": "CAF",
  "South Africa": "CAF",
  "Spain": "UEFA",
  "Sweden": "UEFA",
  "Switzerland": "UEFA",
  "Tunisia": "CAF",
  "Turkiye": "UEFA",
  "United States": "CONCACAF",
  "Uruguay": "CONMEBOL",
  "Uzbekistan": "AFC"
};

export function countryCodeForTeam(teamName: string): string | undefined {
  return COUNTRY_CODES[teamName];
}

export function confederationForTeam(teamName: string) {
  return CONFEDERATIONS[teamName];
}
